remote_theme: bruno-chanrio/materialize-jekyll@1.3
plugins:
- jekyll-remote-theme
- jekyll-last-modified-at
- jemoji

author: Bruno-chanrio 

head-title: Bruno-chanrio 
title: Bruno-chanrio 
logo: /assets/img/Bruno-chanrio_TitleBarLogo_Colorful.png

baseurl: ""    # the subpath of your site, "/blog"
url: ""

# footer 
description: High Quality Software and Android app developer

developedby: true

#
# Custom
#

# Color
# All css class, see: http://materializecss.com/color.html
header-color: "dango-pink-bg darken-2"
head-theme-color: "#FF00AA"     # MUST in hex format, may the same as header-color. This color is for android chrome browser.

footer-color: "dango-pink-bg darken-2"
footer-button-color: "dango-pink-bg darken-4"
footer-link-color: "dango-teal-text text-darken-6"

share-button-color: "dango-teal-bg darken-3"
share-button-small-color: ""

##
#excerpt_separator: <!-- excerpt_end -->       # for post.excerpt
